app/blueprints/characters/__init__.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_login import current_user, login_required

from app import db
from app.blueprints.characters.forms import ListForm
from app.blueprints.characters.models import Character

from .views.character import character

bp = Blueprint('characters', __name__, url_prefix='/characters', template_folder='templates')

@bp.route('/', methods=["GET", "POST"])
@login_required
def index():
    """
    Index for characters.

    Access:
        TBD

    Actions:
        Before character selection:
        - TODO: Users can select from character that have been shared with them.
        - TODO: DMs can select from characters that are a part of their own
                campaigns.
            - TODO: Character sheets should also be viewable in a user's profile
                    to Admins
            - TODO: Viewing all characters sheets should be toggle-able.

        After Character selection:
        - TODO: User can upload a picture of the character.
        - TODO: Upload a 3d character model.
        - TODO: Select campaign for the character.
            - TODO: Select based on DM.
            - TODO: Drop-down.
        - TODO: Add Talespire roll links and buttons.
    """

    # Make character list

    form = ListForm()

    # if request.method == "GET":
    characters = None
    if int(current_user.privilege.level) <= 5:
        characters = Character.query.all()
    else:
        characters = Character.query.filter_by(player_id=current_user.id).all()

    for _char in characters:
        data = dict(
            char_id = _char.id
        )
        form.char.append_entry(data)
        form.char.entries[-1].char_name.label.text = _char.name

    if form.validate_on_submit():

        if form.new_character.data:
            return redirect(url_for('characters.character', character_id="New Character"))

        for _char in form.char.entries:
            if _char.char_name.data:
                return redirect(url_for('characters.character', character_id=_char.char_id.data))
            elif _char.rm_btn.data:
                rm_char = Character.query.filter_by(id=_char.char_id.data).first()
                db.session.delete(rm_char)
                try:
                    db.session.commit()
                except Exception:
                    db.session.rollback()
                return redirect(url_for('characters.character', character_id=""))

    return render_template('characters/list.html', form=form)

bp.add_url_rule('/<character_id>', view_func=character, methods=["GET", "POST"])

app/blueprints/characters/views/character.py
from flask import render_template, request, redirect, url_for

from flask_login import current_user, login_required

from .helpers import CharacterSheet as CS
from app import db
from app.blueprints.characters.models import Character
from app.blueprints.characters.forms import MainForm


@login_required
def character(character_id=None):

    # Get objects
    form = MainForm()
    char = Character.query.filter_by(id=character_id).first()
    cs = CS(char, form)

    # Update Player List
    form.char_info.player.choices = [username[0] for username in db.session.execute('SELECT username from user where 1').all()]

    # Set priviliges
    if int(current_user.privilege.level) > 5:
        form.char_info.player.description['editable'] = False
    else:
        form.char_info.player.description['editable'] = True

    # Set Character
    if not char:
        char = Character(player=current_user)
        db.session.add(char)
        db.session.flush()
        db.session.commit()
        character_id=char.id

        form.char_info.player.data = current_user.username

        cs.load_char(char=char, load_db=False)
        cs.upload()

    else:
        if request.method == "GET":
            cs.load_char()
        if not form.char_info.player.data:
            form.char_info.player.data = char.player.username

    if request.method == "POST":
        if form.validate_on_submit():
            if form.add_class.data:
                cs.add_class()
            elif form.add_weapon.data:
                cs.add_weapon()
            elif form.add_armor.data:
                cs.add_armor()
            elif form.add_shield.data:
                cs.add_shield()
            elif form.add_spell.data:
                cs.add_spell()
            elif form.add_item.data:
                cs.add_item()
            elif form.add_feat.data:
                cs.add_feat()
            elif form.add_special.data:
                cs.add_special()
            elif form.add_language.data:
                cs.add_language()
            elif form.save.data or form.update.data:
                cs.upload()
            else:
                # Check for rm buttons
                check_rm_button(form.class_info, cs.rm_class)
                check_rm_button(form.weapons, cs.rm_weapon)
                check_rm_button(form.armor, cs.rm_armor)
                check_rm_button(form.shields, cs.rm_shield)
                check_rm_button(form.spells, cs.rm_spell)
                check_rm_button(form.items, cs.rm_item)
                check_rm_button(form.feats, cs.rm_feat)
                check_rm_button(form.specials, cs.rm_special)
                check_rm_button(form.languages, cs.rm_language)

            cs.load_char(load_db=False)

        else:
            print("post failed")
            for err in form.errors:
                print(err)

    cs.create_table_feats()
    try:
        if 'New Character' in request.path:
            return redirect(url_for('characters.character', character_id=character_id))
    except Exception as err:
        print(err)
        pass
    return render_template('characters/sheet.html', character_id=character_id, form=form, data=cs.data, tables=cs.tables)

def check_rm_button(form, rm):
    """ Check if the forms delete button has been clicked and removes line item. """

    for i, _form in enumerate(form.entries):
        if _form.bn_del.data:
            rm(i)

app/blueprints/characters/templates/characters/base.html
{% extends "base.html" %}

{% block style %}{% endblock style %}

{% block title %}Characters{% endblock title %}

{% block header %}
    <a href="{{ url_for('characters.index') }}">Characters</a>
{% endblock header %}

{% block content %}
{% endblock content %}

app/blueprints/characters/templates/characters/list.html
{% extends "characters/base.html" %}

{% block content %}
    <form  action="", method="post">
        {{ form.csrf_token }}

        {{ form.new_character }}
        <br><br>

        {% if form.char.entries %}
            <table>
                <thead>
                    <tr>
                        <th>Character</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for _char in form.char.entries %}
                        <tr>
                            <td>{{ _char.char_name }}</td>
                            <td>{{ _char.rm_btn }}</td>
                            <td>{{ _char.char_id }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </form>
{% endblock content %}

app/blueprints/characters/templates/characters/not_found.html
{% extends "characters/base.html" %}

{% block content %}
    <p>The Character selected could not be found. Please contact an Admin.</p>
{% endblock content %}

app/blueprints/characters/templates/characters/sheet.html
{% extends "characters/base.html" %}

{% from "_render_form_as_table.html" import render_form %}
{% from "_render_form_as_table.html" import render_records %}
{% from "_render_form_as_table.html" import render_headers %}

{% block title %}{{ form.char_info.char_name.data }}{% endblock title %}

{% block content %}
    <form method=post class='CharSheet' id="CharSheetForm">
        {{ form.csrf_token }}

        {# Submit #}
        {% include "characters/sheet/submit.html" %}
        <hr>

        {# Character Info #}
        {% include "characters/sheet/char_info.html" %}
        <hr>

        {# Class and Level #}
        {% include "characters/sheet/class_info.html" %}
        <hr>

        {# Character Stats #}
        {% include "characters/sheet/char_stats.html" %}
        <hr>

        {# AC #}
        {% include "characters/sheet/armor_class.html" %}
        <hr>

        {# Inititive #}
        {% include "characters/sheet/inititive.html" %}
        <hr>

        {# Abilities #}
        {% include "characters/sheet/abilities.html" %}
        <hr>

        {# Skills #}
        {% include "characters/sheet/skills.html" %}
        <hr>

        {# Weapon #}
        {% include "characters/sheet/weapons.html" %}
        <hr>

        {# Armor #}
        {% include "characters/sheet/armor.html" %}
        <hr>

        {# Shields #}
        {% include "characters/sheet/shields.html" %}
        <hr>

        {# Spells #}
        {% include "characters/sheet/spells.html" %}
        <hr>

        {# Items #}
        {% include "characters/sheet/items.html" %}
        <hr>

        {# Money #}
        {% include "characters/sheet/money.html" %}
        <hr>

        {# Feats #}
        {% include 'characters/sheet/feats.html' %}
        <hr>

        {# Specials #}
        {% include "characters/sheet/specials.html" %}
        <hr>

        {# Languages #}
        {% include "characters/sheet/languages.html" %}
        <hr>

        {# Notes #}
        {% include "characters/sheet/notes.html" %}
        <hr>

        {# Submit #}
        {% include "characters/sheet/submit.html" %}
    </form>
{% endblock content %}