app/blueprints/library/models/__init__.py
from .spells import SpellModel

app/blueprints/library/models/spells.py
from sqlalchemy.orm import relationship

from app import db

class SpellModel(db.Model):
    __tablename__ = 'spells'

    # Columns
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(64), unique=True)
    typ = db.Column(db.String(64))
    comp = db.Column(db.String(64))
    time = db.Column(db.String(32))
    rng = db.Column(db.String(32))
    eta = db.Column(db.String(128))
    duration = db.Column(db.String(32))
    save = db.Column(db.String(32))
    resistance = db.Column(db.String(128))
    level = db.Column(db.String(64))
    mana = db.Column(db.Integer)
    desc = db.Column(db.Text())
    wiki = db.Column(db.String(128))

app/blueprints/library/forms/__init__.py
from .spells import SpellForm

app/blueprints/library/forms/spells.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, HiddenField, Form, FieldList, FormField

class SpellSubForm(Form):

	name = StringField()
	typ = StringField()
	comp = StringField()
	time = StringField()
	rng = StringField()
	eta = StringField()
	duration = StringField()
	save = StringField()
	resistance = StringField()
	level = StringField()
	mana = IntegerField()
	desc = StringField()
	wiki = StringField()
	edit = SubmitField()
	remove = SubmitField()
	id = HiddenField()

	class meta:
		csrf = False


class SpellForm(FlaskForm):
	subform = FieldList(FormField(SpellSubForm))
	add_spell = SubmitField(label='Add Spell')

app/blueprints/library/__init__.py
from flask import abort, Blueprint, render_template

from .models import *

bp = Blueprint('library', __name__, url_prefix='/library', template_folder='templates')

@bp.route('')
def index():
    return render_template('library/index.html')

from .views.spells import spells

bp.add_url_rule('spells', view_func=spells, methods=["GET", "POST"])

app/blueprints/library/tables/__init__.py
from .spells import SpellItem, SpellTable

app/blueprints/library/views/spells.py
from flask import render_template, request

from app.blueprints.library.forms import SpellForm
from app.blueprints.library.models import SpellModel
from app.blueprints.library.tables import SpellItem, SpellTable

def spells():

	form = SpellForm()
	table = spellsList(form)

	if request.method == 'POST':
		# print(request.form)
		# spellsAdd()
		pass
	return render_template('library/list.html', table=table, form=form)


def spellsList(form):
	if request.method == 'GET':
		for record in SpellModel.query.all():
			form.subform.append_entry(record)

	table = SpellTable(form.subform)
	print(table)
	return table


# def spellsAdd():
# 	print('check')
# 	return

app/blueprints/library/templates/library/index.html
{% from '_render_field.html' import render_field %}
{% from '_render_errors.html' import render_errors %}

{% extends "base.html" %}

{% block content %}
    {{ render_errors()}}

    <h2>Welcome to the Library</h2>
    <p>Here you will find all the information necessary to complete your campaign.</p>

    <ul>
        <a href="{{ url_for('library.spells') }}">Spells</a>
    </ul>

{% endblock content %}

app/blueprints/library/templates/library/list.html
{% extends "base.html" %}

{% from "_render_errors.html" import render_errors %}

{% block style %}
    <link rel="stylesheet" href="{{ url_for('library.', filename='style.css') }}">
{% endblock style %}

{% block content %}
    {{ render_errors() }}


    <form action="" method="POST">
        {{ table }}
        {{ form.add_spell }}
    </form>
{% endblock content %}