app/blueprints/home/__init__.py
from flask import Blueprint, render_template
from flask_login import current_user

from app.blueprints.auth import is_admin, is_dm

bp = Blueprint('home', __name__, url_prefix='/home', template_folder='templates')

@bp.route('')
def index(user=None, admin=False, dm=False):
    """
    The HOME page for the website.

    Access:
        Everyone

    Currently DM and ADMIN only links are only visible to their respective
        tiers. When the page permissions are implemented the links will be
        available to everyone who has read access.
    """

    if current_user.is_authenticated:
        user=current_user
    if is_admin():
        admin=True
        dm=True
    elif is_dm():
        dm=True

    return render_template('home/index.html', user=user, admin=admin, dm=dm)

app/templates/_render_errors.html
{% macro render_errors() %}
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
        {% if errors %}
            {% for err in errors %}
                <p class="error">{{ err | safe }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endmacro %}

app/templates/_render_field.html
{% macro render_field(field) %}
    {% if field.errors %}
        {% for error in field.errors %}
            <br>
            <span class="error">{{ error }}</span>
            <br>
        {% endfor %}
    {% else %}
        <br>
    {% endif %}
    {{ field.label }}:
    <br>
    {{ field(**kwargs) | safe }}
    <br>
{% endmacro %}

app/templates/_render_form_as_table.html
{% macro render_form(form) %}
        {{ render_headers(form) }}
        {{ render_records(form) }}
{% endmacro %}

{% macro render_headers(form) %}
    <thead>
        <tr>
            {% for field in form %}
                {% if field.description["header"] %}
                    <th>
                        {% if not field.description["button"] %}
                            {{ field.label }}
                        {% endif %}
                    </th>
                {% endif %}
            {% endfor %}
        </tr>
    </thead>
{% endmacro %}

{% macro render_records(form) %}
    <tbody>
        <tr>
            {% for field in form %}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <br>
                        <span class="error">{{ field.label }}: {{ error }}</span>
                        <br>
                    {% endfor %}
                {% endif %}
                {% if field.description["record"] %}
                    <td>
                        {% if field.description["alt_total"] %}
                            {{ form.alt_total.data }}
                        {% else %}
                            {% if field.description["editable"] %}
                                {{ field }}
                            {% else %}
                                {% if field.description["talespire"] %}
                                    <a href="{{ form.talespire }}">
                                {% endif %}
                                {% if not field.description["talespire_alt"] %}
                                    {{ field.data }}
                                {% endif %}
                                {% if field.description["talespire"] %}
                                    </a>
                                {% endif %}
                                {% if form.talespire_alt_bool %}
                                    {% if field.description["talespire_alt"] %}
                                        &nbsp/&nbsp
                                        <a href="{{ form.talespire_alt }}">
                                            {{ field.data }}
                                        </a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </td>
                {% endif %}
            {% endfor %}
        <tr>
    </tbody>
{% endmacro %}

app/templates/_render_table.html
{# render_table will dynamically gerneate a table if it is passed a tuple of 
header and record data. The macro assumes that the headers are a list of 
class tableElements and the records are a list of record rows with each row 
containing a list of tableElemtents for each column in the row. #}

{% macro render_table(table) %}
    {% if table %}

        {% set headers, records, css = table.get_table() %}

        <table {{ css | safe }}>
            <thead>
                <tr>
                    {% for head in headers %}
                        {% if head.link %}
                            <a href="{{ head.link | safe }}">
                        {% endif %}
                            <th>
                                <span {{ head.css | safe }} 
                                    {% if head.hover %}
                                        title="{{ head.hover | safe }}"
                                    {% endif %}
                                >
                                    {{ head.data }}
                                </span>
                            </th>
                        {% if head.link %}
                            </a>
                        {% endif %}
                    {% endfor %}                
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                    <tr>
                    {% for _record in record %}
                        {% if _record.link %}
                            <a href="{{ _record.link | safe }}">
                        {% endif %}
                            <td>
                                <span {{ _record.css | safe }} 
                                    {% if _record.hover %}
                                        title="{{ _record.hover | safe }}"
                                    {% endif %}
                                >   {% if _record.is_table %}
                                        {{ render_table(_record.data) }}
                                    {% else %}
                                        {{ _record.data }}
                                    {% endif %}
                                </span>
                            </td>
                        {% if _record.link %}
                            </a>
                        {% endif %}
                    {% endfor %}                
                </tr>
                {% endfor %}
            </tbody>
        </table>

    {% endif %}
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>

<html lang="en">

    <title>DMC - {% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    {% block style %}{% endblock style %}

    <nav>
        <h1 class="title">
            <a href="{{ url_for('home.index') }}">DM Compainion</a>
        </h1>
        {% block page_title %}{% endblock page_title %}
    </nav>

    <header class="header">
        <h3>{% block header %}{% endblock header %}</h3>
    </header>

    <section class="content">
        {% block content %}{% endblock content %}
    </section>

    <footer>

    </footer>

</html>

app/templates/default.html
{% extends "base.html" %}

{% block style %}

{% endblock style %}

{% block header %}{% block title %}

{% endblock title %}{% endblock header %}

{% block content %}

{% endblock content %}